framework:
    cache:
        app: cache.adapter.filesystem
        pools:
            cache.kibarejob_feed:
                adapter: cache.adapter.filesystem
                default_lifetime: '%env(int:REDIS_CACHE_TTL)%'
            cache.kibarejob_stats:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
